### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by stefanowolfs** [zsajjad/react-native-text-detector#12]
My build fails here:

Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app
Could not find google-services.json while looking in [src/nullnull/debug, src
/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCol
lection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'
.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :react-native-text-detector.
     Required by:
         project :app
      > Unable to find a matching configuration of project :react-native-text-detector: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 38s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: ./gradlew installDebug

Error: Command failed: ./gradlew installDebug
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:13)
    at runOnAllDevices (/home/stefano/devel/ocr/node_modules/react-native/local-cli/runAndroid/runAndroid.js:299:19)
    at buildAndRun (/home/stefano/devel/ocr/node_modules/react-native/local-cli/runAndroid/runAndroid.js:135:12)
    at isPackagerRunning.then.result (/home/stefano/devel/ocr/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Warmachine13** [comment]
You need create your app in firebase and get google-services.json and put in your project 

https://forum.ionicframework.com/t/could-not-find-google-services-json-while-looking-in-src-nullnull-debug-src-debug-nullnull-src-nullnull-src-debug-src-nullnulldebug/126299/6
