### ISSUE TITLE
Attempt to invoke virtual method

### ISSUE THREAD

**Issue by bymuh** [zsajjad/react-native-text-detector#38]
```java
 java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.ml.vision.text.FirebaseVisionTextRecognizer.processImage(com.google.firebase.ml.vision.common.FirebaseVisionImage)' on a null object reference
        at com.fetchsky.RNTextDetector.RNTextDetectorModule.detectFromUri(RNTextDetectorModule.java:49)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by mukesh1430** [comment]
Hi , have you found the solution?
I am facing the same issue.
